#!/bin/bash -eu
>&2 echo "For your convenience: 
  
    var s = document.createElement('script');
    s.src = 'http://localhost:29684/client-dev.js';
    document.body.appendChild(s);";
set -vx

(babel \
    --stage 1 \
    --watch \
    --source-maps inline \
    client-src/ \
    --out-dir dist/)&

(watchify \
    client-src/main.js \
    -t [ babelify --stage 1 ] \
    --debug \
    --outfile dist/client-dev.js)&

(http-server \
    dist/ \
    -a localhost \
    -p 29684 \
    -c -1);
