#!/bin/bash -eu
>&2 echo "For your convenience: 
  
    var s = document.createElement('script');
    s.src = 'http://localhost:29684/all.js';
    document.body.appendChild(s);";
set -vx

cd "$(dirname $0)"

npm install --dev  .

rm -rf client-dist/

mkdir -p client-dist/{html,js}

cp client-src/broadcaster.html client-dist/broadcaster.html

(node_modules/.bin/babel \
    --stage 1 \
    --watch \
    --source-maps inline \
    client-src/ \
    --out-dir client-dist/)&

(node_modules/.bin/watchify \
    client-src/main.js \
    -t [ babelify --stage 1 ] \
    --debug \
    --outfile client-dist/compiled.js)&

(babel-node server-src/main.js);

